apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-service-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi-premium-retain
  resources:
    requests:
      storage: 32Gi
